import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { copyFileSync, cpSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const PNG_SIG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

function readPngIhdrSize(absPath: string): { w: number; h: number } {
  const buf = readFileSync(absPath);
  if (buf.length < 29) return { w: 32, h: 32 };
  if (!buf.subarray(0, 8).equals(PNG_SIG)) return { w: 32, h: 32 };
  if (buf.subarray(12, 16).toString("ascii") !== "IHDR") return { w: 32, h: 32 };
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}

/** Optional emoji previews in the popup (filename stem → emoji). */
const KNIGHT_PREVIEW: Record<string, string> = {
  archer: "🏹",
  cavalry: "🐎",
  paladin: "🛡️",
  peasant: "🌾",
  pikeman: "🔱",
  swordsman: "⚔️",
};

/** Popup list order for knight cursors (filename stem → sort key). */
const KNIGHT_ORDER: Record<string, number> = {
  peasant: 0,
  archer: 1,
  pikeman: 2,
  swordsman: 3,
  cavalry: 4,
  paladin: 5,
};

const BARBARIAN_PREVIEW: Record<string, string> = {
  cyclops: "👁️",
  goblin: "👺",
  ogre: "👹",
  orc: "🪓",
  troll: "🧌",
  wolf: "🐺",
};

/** Popup list order for barbarian cursors (filename stem → sort key). */
const BARBARIAN_ORDER: Record<string, number> = {
  goblin: 0,
  orc: 1,
  wolf: 2,
  ogre: 3,
  troll: 4,
  cyclops: 5,
};

const SORCERESS_PREVIEW: Record<string, string> = {
  druid: "🌿",
  dwarf: "⛏️",
  elf: "🧝",
  phoenix: "🔥",
  sprite: "✨",
  unicorn: "🦄",
};

/** Popup list order for sorceress cursors (filename stem → sort key). */
const SORCERESS_ORDER: Record<string, number> = {
  sprite: 0,
  dwarf: 1,
  elf: 2,
  druid: 3,
  unicorn: 4,
  phoenix: 5,
};

const WARLOCK_PREVIEW: Record<string, string> = {
  centaur: "🏹",
  dragon: "🐉",
  gargoyle: "🗿",
  griffin: "🦅",
  hydra: "🐍",
  minotaur: "🐂",
};

/** Popup list order for warlock cursors (filename stem → sort key). */
const WARLOCK_ORDER: Record<string, number> = {
  centaur: 0,
  gargoyle: 1,
  griffin: 2,
  minotaur: 3,
  hydra: 4,
  dragon: 5,
};

function titleFromStem(stem: string): string {
  return stem.replace(/[_-]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

type CursorPackGenOptions = {
  pluginName: string;
  /** Folder under `public/` after `cursors/`, e.g. `knight` → `public/cursors/knight` */
  packFolder: string;
  outFile: string;
  idPrefix: string;
  labelPrefix: string;
  typeName: string;
  exportConst: string;
  previews: Record<string, string>;
  defaultPreview: string;
  /** Filename stem (lowercase) → popup sort key; stems omitted keep alphabetical index among PNGs. */
  orders?: Record<string, number>;
};

function generateCursorPackPlugin(opts: CursorPackGenOptions): Plugin {
  return {
    name: opts.pluginName,
    buildStart() {
      const packDir = resolve(__dirname, "public/cursors", opts.packFolder);
      const outFile = resolve(__dirname, opts.outFile);
      let files: string[] = [];
      try {
        files = readdirSync(packDir)
          .filter((f) => f.toLowerCase().endsWith(".png"))
          .sort((a, b) => a.localeCompare(b, "en"));
      } catch {
        files = [];
      }

      const lines: string[] = [
        `/** Auto-generated by Vite plugin \`${opts.pluginName}\`. Do not edit by hand. */`,
        "",
        `export type ${opts.typeName} = {`,
        "  id: string;",
        "  pathFromRoot: string;",
        "  label: string;",
        "  preview: string;",
        "  hotX: number;",
        "  hotY: number;",
        "  order: number;",
        "};",
        "",
        `export const ${opts.exportConst}: ${opts.typeName}[] = [`,
      ];

      const orders = opts.orders ?? {};
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const abs = join(packDir, file);
        const { w, h } = readPngIhdrSize(abs);
        const stem = file.replace(/\.png$/i, "");
        const stemKey = stem.toLowerCase();
        const id = `${opts.idPrefix}-${stemKey.replace(/[^a-z0-9]+/g, "-")}`;
        const label = `${opts.labelPrefix} · ${titleFromStem(stem)}`;
        const preview = opts.previews[stemKey] ?? opts.defaultPreview;
        const order = orders[stemKey] ?? i;
        const hotX = Math.max(0, Math.min(Math.floor(w / 2), w - 1));
        const hotY = Math.max(0, Math.min(Math.floor(h * 0.1), h - 1));
        lines.push(
          `  { id: ${JSON.stringify(id)}, pathFromRoot: ${JSON.stringify(`cursors/${opts.packFolder}/${file}`)}, label: ${JSON.stringify(label)}, preview: ${JSON.stringify(preview)}, hotX: ${hotX}, hotY: ${hotY}, order: ${order} },`,
        );
      }

      lines.push("];", "");
      mkdirSync(dirname(outFile), { recursive: true });
      writeFileSync(outFile, lines.join("\n"), "utf8");
    },
  };
}

function copyManifest(): Plugin {
  return {
    name: "copy-manifest",
    closeBundle() {
      copyFileSync(resolve(__dirname, "manifest.json"), resolve(__dirname, "dist/manifest.json"));
      cpSync(resolve(__dirname, "icons"), resolve(__dirname, "dist/icons"), {
        recursive: true,
        filter: (src) => !src.endsWith(".DS_Store"),
      });
    },
  };
}

export default defineConfig({
  plugins: [
    react(),
    generateCursorPackPlugin({
      pluginName: "generate-knight-cursors",
      packFolder: "knight",
      outFile: "src/generated/knightCursors.ts",
      idPrefix: "knight",
      labelPrefix: "Knight",
      typeName: "KnightCursorSpec",
      exportConst: "KNIGHT_CURSOR_SPECS",
      previews: KNIGHT_PREVIEW,
      defaultPreview: "♞",
      orders: KNIGHT_ORDER,
    }),
    generateCursorPackPlugin({
      pluginName: "generate-barbarian-cursors",
      packFolder: "barbarian",
      outFile: "src/generated/barbarianCursors.ts",
      idPrefix: "barbarian",
      labelPrefix: "Barbarian",
      typeName: "BarbarianCursorSpec",
      exportConst: "BARBARIAN_CURSOR_SPECS",
      previews: BARBARIAN_PREVIEW,
      defaultPreview: "🗡️",
      orders: BARBARIAN_ORDER,
    }),
    generateCursorPackPlugin({
      pluginName: "generate-sorceress-cursors",
      packFolder: "sorceress",
      outFile: "src/generated/sorceressCursors.ts",
      idPrefix: "sorceress",
      labelPrefix: "Sorceress",
      typeName: "SorceressCursorSpec",
      exportConst: "SORCERESS_CURSOR_SPECS",
      previews: SORCERESS_PREVIEW,
      defaultPreview: "🔮",
      orders: SORCERESS_ORDER,
    }),
    generateCursorPackPlugin({
      pluginName: "generate-warlock-cursors",
      packFolder: "warlock",
      outFile: "src/generated/warlockCursors.ts",
      idPrefix: "warlock",
      labelPrefix: "Warlock",
      typeName: "WarlockCursorSpec",
      exportConst: "WARLOCK_CURSOR_SPECS",
      previews: WARLOCK_PREVIEW,
      defaultPreview: "😈",
      orders: WARLOCK_ORDER,
    }),
    copyManifest(),
  ],
  build: {
    outDir: "dist",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        popup: resolve(__dirname, "popup.html"),
        content: resolve(__dirname, "src/content/index.ts"),
      },
      output: {
        entryFileNames: "[name].js",
        chunkFileNames: "chunks/[name].js",
        assetFileNames: "assets/[name][extname]",
      },
    },
  },
});
